<?php
return array(
	'smsKey'=>array(
		'title'=>'短信账号<span style="color:#FF6666;">【购买短信服务请点击<a target="_blank" href="http://www.alidayu.com/">阿里大于</a>购买】',
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'smsPass'=>array(
		'title'=>'短信密码',
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'signature'=>array(
		'title'=>'短信签名',
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_USER_REGISTER_VERFIY'=>array(
		'title'=>'用户注册验证码模板ID',
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_BIND'=>array(
		'title'=>'绑定手机提醒模板ID',
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_EDIT'=>array(
		'title'=>"更改手机提醒模板ID",
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_FOTGET'=>array(
		'title'=>"忘记密码模板ID",
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_SHOP_REGISTER_VERFIY'=>array(
		'title'=>'商家开店验证码模板ID',
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_SHOP_OPEN_SUCCESS'=>array(
		'title'=>"游客开店成功提醒模板ID",
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_USER_SHOP_OPEN_SUCCESS'=>array(
		'title'=>"会员开店成功提醒模板ID",
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_SHOP_OPEN_FAIL'=>array(
		'title'=>"开店失败提醒模板ID",
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	)
);
